index:
    path:      /
    defaults:  { _controller: FootballBundle:Default:index }

country:
    path:      country/{name}
    defaults:  { _controller: FootballBundle:Default:country }
    requirements:
        name:  en|fr

player:
    path:      player/{country}/{id}
    defaults:  { _controller: FootballBundle:Default:player }

coach:
    path:      coach/{country}
    defaults:  { _controller: FootballBundle:Default:coach }

team:
    path:      team/{name}
    defaults:  { _controller: FootballBundle:Default:team }
    requirements:
        name:  en|fr