index:
    path:      /
    defaults:  { _controller: FootballBundle:Default:index }

country:
    path:      country/{name}
    defaults:  { _controller: FootballBundle:Default:country }
    requirements:
        name:  en|fr

player:
    path:      player/{country}/{id}
    defaults:  { _controller: FootballBundle:Default:player }
    requirements:
        country:  en|fr
        id:  \d+

coach:
    path:      coach/{country}
    defaults:  { _controller: FootballBundle:Default:coach }
    requirements:
        country: en|fr

team:
    path:      team/{name}
    defaults:  { _controller: FootballBundle:Default:team }
    requirements:
        name:  en|fr