#football:
#    resource: "@FootballBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
app:
    resource: "@FootballBundle/Resources/config/routing.yml"